- hosts: all
  vars:
    library_path: "{{ zuul.project.src_dir }}/{{ java_libraries[0].context }}"

  tasks:
    - name: Clean and prepare release
      command: mvn release:clean release:prepare
      args:
        chdir: "{{ library_path }}"
      environment:
        MAVEN_HOME: "/opt/apache-maven-3.8.8"
        PATH: "{{ ansible_env.PATH }}:/opt/apache-maven-3.8.8/bin"
      become: yes

    - name: Perform release
      command: mvn release:perform
      args:
        chdir: "{{ library_path }}"
      environment:
        MAVEN_HOME: "/opt/apache-maven-3.8.8"
        PATH: "{{ ansible_env.PATH }}:/opt/apache-maven-3.8.8/bin"
      become: yes
